spring.application.name=user-service
server.port=8080

# JWT (same algorithm, different secret value per env)
app.jwt.expiration=86400000

# OTP
app.otp.expiry-seconds=600

# Active profile
spring.profiles.active=local