# Database ? AWS RDS
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA ? strict for prod
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Redis ? AWS ElastiCache
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=6379

# JWT secret ? strong, injected from AWS Secrets Manager
app.jwt.secret=${JWT_SECRET}

## Mail ? AWS SES
#spring.mail.host=email-smtp.ap-northeast-1.amazonaws.com
#spring.mail.port=587
#spring.mail.username=${AWS_SES_SMTP_USER}
#spring.mail.password=${AWS_SES_SMTP_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# Mail ? Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USER}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true